# name: Version Check
# on:
#   pull_request:

# jobs:
#   master-pr-check-version:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: dkershner6/npm-version-check-with-comment-action@v1
#         id: version-check
#         with:
#           github-token: "${{ secrets.ACCESS_TOKEN }}"

#       # Outputs whether or not it changed
#       - run: echo ${{ steps.version-check.outputs.version-did-change }}

#       # Optionally fail the workflow, should you choose
#       - name: Fail on no version updated
#         if: ${{ steps.version-check.outputs.version-did-change == 'false' }}
#         run: 'echo "No version change :/" && exit 1'
