name: Release Pipeline
on:
  release:
    types: created

jobs:
  build-and-publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get git tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Replace CDN_UPLOAD_USER
        uses: jwsi/secret-parser@v1
        with:
          filename: .github/workflows/scripts/downloadImagesAndFonts.sh
          secret-name: "CDN_UPLOAD_USER"
          secret-value: ${{ secrets.CDN_UPLOAD_USER }}
      - name: Replace CDN_UPLOAD_SECRET
        uses: jwsi/secret-parser@v1
        with:
          filename: .github/workflows/scripts/downloadImagesAndFonts.sh
          secret-name: "CDN_UPLOAD_SECRET"
          secret-value: ${{ secrets.CDN_UPLOAD_SECRET }}
      - name: Find and Replace current version
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "current-version"
          replace: ${{ steps.tag.outputs.tag }}
          include: "**downloadImagesAndFonts.sh"
      - name: Replace CDN_UPLOAD_USER for assets upload
        uses: jwsi/secret-parser@v1
        with:
          filename: .github/workflows/scripts/uploadImages.sh
          secret-name: "CDN_UPLOAD_USER"
          secret-value: ${{ secrets.CDN_UPLOAD_USER }}
      - name: Replace CDN_UPLOAD_SECRET for assets upload
        uses: jwsi/secret-parser@v1
        with:
          filename: .github/workflows/scripts/uploadImages.sh
          secret-name: "CDN_UPLOAD_SECRET"
          secret-value: ${{ secrets.CDN_UPLOAD_SECRET }}
      - name: Find and Replace current version
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "current-version-suffix"
          replace: ${{ steps.tag.outputs.tag }}
          include: "**uploadImages.sh"
      - name: Find and Replace current version
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "vidis-cdn-snapshots"
          replace: "vidis-cdn"
          include: "**uploadImages.sh"
      - name: Publish Release
        run: |
          echo "Version ${{ steps.tag.outputs.tag }}"
          echo "Getting corresponding release candidate..."
          curl -OL https://fwu-nexus.intension.eu/repository/vidis-cdn-snapshots/${{ steps.tag.outputs.tag }}-rc/vidisLogin.umd.js
          curl -v -u ${{ secrets.CDN_UPLOAD_USER }}:${{ secrets.CDN_UPLOAD_SECRET }} --upload-file vidisLogin.umd.js https://fwu-nexus.intension.eu/repository/vidis-cdn/${{ steps.tag.outputs.tag }}/vidisLogin.umd.js
          rm -rf dist
          echo "Testing downloading images and fonts..."
          sh .github/workflows/scripts/downloadImagesAndFonts.sh
          echo "Uploading images and fonts for release ..."
          sh .github/workflows/scripts/uploadReleaseAssets.sh
