name: Dev Vidis Button Service Pipelines
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Run Tests
        run: |
          npm install -g npm@8
          npm ci
          echo "Running unit tests. The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          npm run test:unit -- --coverage
          echo "This job's status is ${{ job.status }}."
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage/lcov-report/index.html

  build-and-publish:
    needs: run-unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Replace CDN_UPLOAD_USER
        uses: jwsi/secret-parser@v1
        with:
          filename: .github/workflows/scripts/uploadImagesAndFonts.sh
          secret-name: "CDN_UPLOAD_USER"
          secret-value: ${{ secrets.CDN_UPLOAD_USER }}
      - name: Replace CDN_UPLOAD_SECRET
        uses: jwsi/secret-parser@v1
        with:
          filename: .github/workflows/scripts/uploadImagesAndFonts.sh
          secret-name: "CDN_UPLOAD_SECRET"
          secret-value: ${{ secrets.CDN_UPLOAD_SECRET }}
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "current-version"
          replace: ${{ steps.package-version.outputs.current-version}}
          include: "**uploadImagesAndFonts.sh"
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "-suffix"
          replace: "-snapshot"
          include: "**uploadImagesAndFonts.sh"
      - name: Publish npm and CDN
        run: |
          npm install -g npm@8
          npm ci
          echo "Running build job on branch ${{ github.ref }}."
          npm run build
          echo ${{ github.ref }} | sed 's/.*\///'
          curl -v -u ${{ secrets.CDN_UPLOAD_USER }}:${{ secrets.CDN_UPLOAD_SECRET }} --upload-file dist/vidisLogin.umd.js https://fwu-nexus.intension.eu/repository/vidis-cdn-snapshots/${{ steps.package-version.outputs.current-version}}-snapshot/vidisLogin.umd.js
          curl -v -u ${{ secrets.CDN_UPLOAD_USER }}:${{ secrets.CDN_UPLOAD_SECRET }} --upload-file dist/vidisLogin.umd.min.js https://fwu-nexus.intension.eu/repository/vidis-cdn-snapshots/${{ steps.package-version.outputs.current-version}}-snapshot/vidisLogin.umd.min.js
          curl -v -u ${{ secrets.CDN_UPLOAD_USER }}:${{ secrets.CDN_UPLOAD_SECRET }} --upload-file dist/vidisLogin.umd.min.js.br https://fwu-nexus.intension.eu/repository/vidis-cdn-snapshots/${{ steps.package-version.outputs.current-version}}-snapshot/vidisLogin.umd.min.js.br
          curl -v -u ${{ secrets.CDN_UPLOAD_USER }}:${{ secrets.CDN_UPLOAD_SECRET }} --upload-file dist/vidisLogin.umd.min.js.gz https://fwu-nexus.intension.eu/repository/vidis-cdn-snapshots/${{ steps.package-version.outputs.current-version}}-snapshot/vidisLogin.umd.min.js.gz
          echo "Uploading images and fonts..."
          sh .github/workflows/scripts/uploadImagesAndFonts.sh
          echo "Publishing..."
          echo ${{ secrets.NPMRC }} | base64 -d > .npmrc
          npm publish

  run-selenium-tests-with-chrome:
    needs: build-and-publish
    runs-on: ubuntu-latest
    env:
      TEST_CICD: "true"
      ENVIRONMENT: "DEV"
      TESTPAGE_HOST: ${{ secrets.TESTPAGE_HOST }}
      TAKE_SCREENSHOTS: "true"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Install node modules and run selenium script
        run: |
          cd tests/selenium
          npm install -g npm@8
          npm ci
          npm run test:chrome

  run-accessibility-tests-with-chrome:
    needs: build-and-publish
    runs-on: ubuntu-latest
    env:
      TEST_CICD: "true"
      ENVIRONMENT: "DEV"
      TESTPAGE_HOST: ${{ secrets.TESTPAGE_HOST }}
      TAKE_SCREENSHOTS: "false"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Install node modules and run selenium script
        continue-on-error: true
        run: |
          cd tests/selenium
          npm install -g npm@8
          npm ci
          npm run accessibility:github
