name: Dev Vidis Button Service Pipelines
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Run Tests
        run: |
          npm install -g npm@8
          npm install
          echo "Running unit tests. The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          npm run test:unit -- --coverage
          echo "This job's status is ${{ job.status }}."
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage/lcov-report/index.html

  build-and-publish:
    needs: run-unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Publish
        run: |
          npm install -g npm@8
          npm install
          echo "Running build job on branch ${{ github.ref }}."
          npm run build
          echo "Publishing..."
          echo ${{ secrets.NPMRC }} | base64 -d > .npmrc
          npm publish