name: Main Vidis Button Service Pipelines
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Run Tests
        run: |
          npm install -g npm@8
          npm install
          echo "Running unit tests. The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          npm run test:unit -- --coverage
          echo "This job's status is ${{ job.status }}."
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage/lcov-report/index.html

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Build
      run: |
        npm install -g npm@8
        npm install
        echo "Running build job on branch is ${{ github.ref }}."
        npm run build
        echo "This job's status is ${{ job.status }}."
    - name: Set and check outputs
      id: vars
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        echo ${{ steps.vars.outputs.sha_short }}
    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build_artifacts_${{ steps.vars.outputs.sha_short }}
        path: dist