name: Dev Vidis Button Service Pipelines
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Run Tests
        run: |
          npm install -g npm@8
          npm ci
          echo "Running unit tests. The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          npm run test:unit -- --coverage
          echo "This job's status is ${{ job.status }}."
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage/lcov-report/index.html

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Get main version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: 
        run: |
          echo "Current version in main branch is ${{ steps.package-version.outputs.current-version}}"
      - name: Get Feature Branch Version
        uses: thebongy/version-check@v1
        id: version_check_staging
        with:
          file: package.json
      - name:
        run: |
          echo "Feature branch version is ${{steps.version_check_staging.outputs.rawVersion}}"

  master-pr-check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check if version changed
        uses: rpiambulance/action-pr-version-check
        with:
          file: package.json # optional, defaults to "package.json"