name: Main Vidis Button Service Pipelines
on:
  push:
    branches:
      - main

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Run Tests
        run: |
          npm install -g npm@8
          npm ci
          echo "Running unit tests. The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          npm run test:unit -- --coverage
          echo "This job's status is ${{ job.status }}."
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage/lcov-report/index.html
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Run Audit Level critical
        run: |
          npm install -g npm@8
          npm audit fix
          npm audit --audit-level=critical
          echo "This job's status is ${{ job.status }}."
        continue-on-error: true

  create-rc-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create RC Tag
        uses: butlerlogic/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.ACCESS_TOKEN }}"
          tag_suffix: "-rc"

  build-and-publish-rc:
    needs: create-rc-tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Find and Replace current version
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "current-version"
          replace: ${{ steps.package-version.outputs.current-version}}
          include: "**uploadImagesAndFonts.sh"
      - name: Find and Replace suffix
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "-suffix"
          replace: "-rc"
          include: "**uploadImagesAndFonts.sh"
      - name: Publish npm and CDN
        env:
          CDN_UPLOAD_USER: ${{ secrets.CDN_UPLOAD_USER }}
          CDN_UPLOAD_SECRET: ${{ secrets.CDN_UPLOAD_SECRET }}
        run: |
          npm install -g npm@8
          npm ci
          echo "Running build job on branch ${{ github.ref }}."
          npm run build
          echo "Publishing CDN..."
          curl -v -u ${{ secrets.CDN_UPLOAD_USER }}:${{ secrets.CDN_UPLOAD_SECRET }} --upload-file dist/vidisLogin.umd.js https://fwu-nexus.intension.eu/repository/vidis-cdn-snapshots/${{ steps.package-version.outputs.current-version}}-snapshot/vidisLogin.umd.js
          curl -v -u ${{ secrets.CDN_UPLOAD_USER }}:${{ secrets.CDN_UPLOAD_SECRET }} --upload-file dist/vidisLogin.umd.min.js https://fwu-nexus.intension.eu/repository/vidis-cdn-snapshots/${{ steps.package-version.outputs.current-version}}-snapshot/vidisLogin.umd.min.js
          curl -v -u ${{ secrets.CDN_UPLOAD_USER }}:${{ secrets.CDN_UPLOAD_SECRET }} --upload-file dist/vidisLogin.umd.min.js.br https://fwu-nexus.intension.eu/repository/vidis-cdn-snapshots/${{ steps.package-version.outputs.current-version}}-snapshot/vidisLogin.umd.min.js.br
          curl -v -u ${{ secrets.CDN_UPLOAD_USER }}:${{ secrets.CDN_UPLOAD_SECRET }} --upload-file dist/vidisLogin.umd.min.js.gz https://fwu-nexus.intension.eu/repository/vidis-cdn-snapshots/${{ steps.package-version.outputs.current-version}}-snapshot/vidisLogin.umd.min.js.gz
          echo "Uploading images and fonts..."
          sh .github/workflows/scripts/uploadImagesAndFonts.sh
          echo "Publishing npm..."
          echo ${{ secrets.NPMRC }} | base64 -d > .npmrc
          npm config set _auth="$(echo -n '${{ secrets.CDN_UPLOAD_USER }}:${{ secrets.CDN_UPLOAD_SECRET }}' | base64)"
          npm publish
