name: Dev Vidis Button Service Pipelines
on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Compare Version"
        id: compare
        uses: sharesight/compare-package-json-version-with-latest@v1.1.1
        with:
          repository: ${{ github.repository }}

      - name: Debug
        run: |
          echo current_version: ${{ steps.compare.outputs.current_version }}
          echo latest_version: ${{ steps.compare.outputs.latest_version }}
          echo matches?: ${{ steps.compare.outputs.matches }}
          echo newer?: ${{ steps.compare.outputs.newer }}
          echo diff: ${{ steps.compare.outputs.diff }}

      - name: Fail if not newer
        if: steps.compare.outputs.newer != 'true'
        run: |
          echo Version was not newer: ${{ steps.compare.outputs.current_version }} vs. ${{ steps.compare.outputs.latest_version }}
          exit 1
          
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: del-systems/check-if-version-bumped@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

  master-pr-check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: dkershner6/npm-version-check-with-comment-action@v1
        id: version-check
        with:
          github-token: "${{ secrets.ACCESS_TOKEN }}"

      # Outputs whether or not it changed
      - run: echo ${{ steps.version-check.outputs.version-did-change }}
      
      # Optionally fail the workflow, should you choose
      - name: Fail on no version updated
        if: ${{ steps.version-check.outputs.version-did-change == 'false' }}
        run: 'echo "No version change :/" && exit 1'