name: Dev Vidis Button Service Pipelines
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Get main version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: 
        run: |
          echo "Current version in main branch is ${{ steps.package-version.outputs.current-version}}"
      - name: Get Feature Branch Version
        uses: thebongy/version-check@v1
        id: version_check_staging
        with:
          file: package.json
      - name:
        run: |
          echo "Feature branch version is ${{steps.version_check_staging.outputs.rawVersion}}"

  master-pr-check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check if version changed
        uses: rpiambulance/action-pr-version-check
        with:
          file: package.json # optional, defaults to "package.json"