name: Dev Vidis Button Service Pipelines
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  master-pr-check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          GITHUB_TOKEN: "${{ secrets.ACCESS_TOKEN }}"

      - name: "Compare Version"
        id: compare
        uses: sharesight/compare-package-json-version-with-latest@v1.1.1
        with:
          repository: ${{ github.repository }}

      - name: Debug
        run: |
          echo current_version: ${{ steps.compare.outputs.current_version }}
          echo latest_version: ${{ steps.compare.outputs.latest_version }}
          echo matches?: ${{ steps.compare.outputs.matches }}
          echo newer?: ${{ steps.compare.outputs.newer }}
          echo diff: ${{ steps.compare.outputs.diff }}

      - name: Fail if not newer
        if: steps.compare.outputs.newer != 'true'
        run: |
          echo Version was not newer: ${{ steps.compare.outputs.current_version }} vs. ${{ steps.compare.outputs.latest_version }}
          exit 1