name: Dev Vidis Button Service Release Pipeline
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Publish CDN
        run: |
          npm install -g npm@8
          npm install
          echo "Running build job on branch ${{ github.ref }}."
          npm run build
          echo ${{ github.ref }} | sed 's/.*\///'
          curl -v -u ${{ secrets.CDN_UPLOAD_USER }}:${{ secrets.CDN_UPLOAD_SECRET }} --upload-file dist/vidisLogin.umd.js https://fwu-nexus.intension.eu/repository/vidis-cdn/${{ steps.package-version.outputs.current-version}}/vidisLogin.umd.js